# -*- coding: utf-8 -*-
"""2week.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vXlKIXc6N3E0_llYnLohTuwja0hQHdY_
"""

import gdown
gdown.download('https://bit.ly/3eecMKZ','남산도서관 장서 대출목록 (2021년 04월).csv', quiet=False)

with open('남산도서관 장서 대출목록 (2021년 04월).csv') as f:
  print(f.readline())   # open() normally supposes that text files are stored in UTF-8 form. But Korean text files normally use EUC-KR.

# TO know which incoding form is uesd in text file, we'll gonna use chardet.detect() function.
import chardet
with open('남산도서관 장서 대출목록 (2021년 04월).csv', 'rb') as f:
  d = f.readline()
print(chardet.detect(d))

# Now read about the encoding in '2week_concept'
# As you can think, ypu can simply solve this problem. Just change encoding method. It's simple right?
with open('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='EUC-KR') as f:
  print(f.readline())
  print(f.readline())

"""# Actually, Using pandas to read CSV files is more comfortable. But when you open a very big file, Using open() and readline() is a good way to check file quickly"""

# If you want to read CSV in pandas, Use read_csv() function.
import pandas as pd
df = pd.read_csv('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='EUC-KR')

"""##You gonna see ' DtypeWarning: Columns (5,6,9) have mixed types. Specify dtype option on import or set low_memory=False.' It means at 5,6,9 row there's different data type in the same row"""

# You can handle this problem in this way
import pandas as pd
df = pd.read_csv('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='EUC-KR',low_memory=False)

# head() function show 5 row in Dataframe
df.head()

